<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<!DOCTYPE HT_2013-2020 [
	<!ELEMENT HT_2013-2020 (ht-data)>
	<!ELEMENT ht-data (data-year, ori, pub-agency-name, agency-type-name,state-abbr, state-name, division, county-name, region-name,population-group-code)>
	<!ELEMENT data-year (#PCDATA)>
	<!ELEMENT ori (#PCDATA)>
	<!ELEMENT pub-agency-name (#PCDATA)>
	<!ELEMENT agency-type-name (#PCDATA)>
	<!ELEMENT state-abbr (#PCDATA)>
	<!ELEMENT state-name (#PCDATA)>
	<!ELEMENT division (#PCDATA)>
	<!ELEMENT county-name (#PCDATA)>
	<!ELEMENT region-name (#PCDATA)>
	<!ELEMENT population-group-code (#PCDATA)>

	<!ATTLIST ht-data id CDATA #REQUIRED>
]>

<HT_2013-2020>

	<ht-data id ="001">
		<data-year> 2016 </data-year>
		<ori> MO0480600 </ori>
		<pub-agency-name> Independence </pub-agency-name>
		<agency-type-name> City </agency-type-name>
		<state-abbr> MO </state-abbr>
		<state-name> Missouri </state-name>
		<division> West North Central </division>
		<county-name> JACKSON </county-name>
		<region-name> Midwest </region-name>
		<population-group-code> 2 </population-group-code>
	</ht-data>

	<ht-data id ="002">
		<data-year> 2016 </data-year>
		<ori> TX2201200 </ori>
		<pub-agency-name> Fort Worth </pub-agency-name>
		<agency-type-name> City </agency-type-name>
		<state-abbr> TX </state-abbr>
		<state-name> Texas </state-name>
		<division> West South Central </division>
		<county-name> PARKER; DENTON; TARRANT </county-name>
		<region-name> South </region-name>
		<population-group-code> 1B </population-group-code>
	</ht-data>

	<ht-data id ="003">
		<data-year> 2016 </data-year>
		<ori> TX2270100 </ori>
		<pub-agency-name> Austin </pub-agency-name>
		<agency-type-name> City </agency-type-name>
		<state-abbr> TX </state-abbr>
		<state-name> Texas </state-name>
		<division> West North Central </division>
		<county-name> WILLIAMSON; TRAVIS </county-name>
		<region-name> South </region-name>
		<population-group-code> 1B </population-group-code>
	</ht-data>

	<ht-data id ="004">
		<data-year> 2019 </data-year>
		<ori> NV0020100 </ori>
		<pub-agency-name> Las Vegas Metropolitan Police Department </pub-agency-name>
		<agency-type-name> City </agency-type-name>
		<state-abbr> NV </state-abbr>
		<state-name> Nevada </state-name>
		<division> Mountain </division>
		<county-name> CLARK </county-name>
		<region-name> West </region-name>
		<population-group-code> 1A </population-group-code>
	</ht-data>

	<ht-data id ="005">
		<data-year> 2017 </data-year>
		<ori> AZ0070500 </ori>
		<pub-agency-name> Chandler </pub-agency-name>
		<agency-type-name> City </agency-type-name>
		<state-abbr> AZ </state-abbr>
		<state-name> Arizona </state-name>
		<division> Mountain </division>
		<county-name> MARICOPA </county-name>
		<region-name> West </region-name>
		<population-group-code> 2 </population-group-code>
	</ht-data>

	<ht-data id ="006">
		<data-year> 2018 </data-year>
		<ori> ND0090200 </ori>
		<pub-agency-name> Fargo </pub-agency-name>
		<agency-type-name> City </agency-type-name>
		<state-abbr> ND </state-abbr>
		<state-name> North Dakota </state-name>
		<division> West North Central </division>
		<county-name> CASS </county-name>
		<region-name> Midwest </region-name>
		<population-group-code> 2 </population-group-code>
	</ht-data>

	<ht-data id ="007">
		<data-year> 2020 </data-year>
		<ori> GA0380100 </ori>
		<pub-agency-name> Newnan </pub-agency-name>
		<agency-type-name> City </agency-type-name>
		<state-abbr> GA </state-abbr>
		<state-name> Georgia </state-name>
		<division> South Atlantic </division>
		<county-name> COWETA </county-name>
		<region-name> South </region-name>
		<population-group-code> 4 </population-group-code>
	</ht-data>

	<ht-data id ="008">
		<data-year> 2020 </data-year>
		<ori> GA0440200 </ori>
		<pub-agency-name> DeKalb County Police Department </pub-agency-name>
		<agency-type-name> County </agency-type-name>
		<state-abbr> GA </state-abbr>
		<state-name> Georgia </state-name>
		<division> South Atlantic </division>
		<county-name> DEKALB </county-name>
		<region-name> South </region-name>
		<population-group-code> 9A </population-group-code>
	</ht-data>

	<ht-data id ="009">
		<data-year> 2017 </data-year>
		<ori> AZ0071700 </ori>
		<pub-agency-name> Mesa </pub-agency-name>
		<agency-type-name> City </agency-type-name>
		<state-abbr> AZ </state-abbr>
		<state-name> Arizona </state-name>
		<division> Mountain </division>
		<county-name> MARICOPA </county-name>
		<region-name> West </region-name>
		<population-group-code> 1C </population-group-code>
	</ht-data>

	<ht-data id ="010">
		<data-year> 2020 </data-year>
		<ori> LA0260000 </ori>
		<pub-agency-name> Jefferson </pub-agency-name>
		<agency-type-name> County </agency-type-name>
		<state-abbr> LA </state-abbr>
		<state-name> Louisiana </state-name>
		<division> West South Central </division>
		<county-name> JEFFERSON </county-name>
		<region-name> South </region-name>
		<population-group-code> 9A </population-group-code>
	</ht-data>

</HT_2013-2020>
